image: Ubuntu1804 #образдлясборки
stack: node 10 #окружение
branches:
  only:
    - master #веткаgit
cache: node_modules #кеширование
install:
  - yarn install #командаустановкизависимостей
build: off
build_script:
  - yarn run build #командасборки
test_script:
  - yarn lint && yarn run test #скрипттестирования
deploy_script: #скриптразвёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  #- yarn run push-dir --dir=dist --branch=gh-pages --force --verbose
  - yarn run push-dir dir=dist branch=gh-pages force verbose
